Issue489 fixflash
spacetelescope/hstcal pull request #550
Opened 2021-05-06 20:43 UTC by mdlpstsci

Fixed a bug associated with the FLASHDUR computation.  The FLASHDUR keyword was updated in the CRJ/CRC headers to be the sum of the individual input images as this keyword is used in ACS2D to scale the flash reference file for flash correction.

2021-05-06 21:10 UTC, stsci-hack requested changes
The new keyword should have some description when added to the header, just to be nice to the user.

2021-05-06 21:10 UTC, stsci-hack commented on pkg/acs/calacs/acsrej/acsrej_do.c
> +        PutKeyFlt (sg.globalhdr, "FLASHDUR", cumFlashDur, "");
This new keyword should have a comment to explain what it is; specifically, total/cumulative flash duration in seconds (or minutes or hours or mjd? ).

2021-05-11 19:40 UTC, stsci-hack commented on pkg/acs/calacs/acsrej/acsrej_do.c
> +        PutKeyFlt (sg.globalhdr, "FLASHDUR", cumFlashDur, "");
That's fine.

2021-05-11 19:40 UTC, stsci-hack approved these changes
LGTM

2021-05-12 15:08 UTC, merged

2021-05-12 15:12 UTC, mdlpstsci commented
Resolves Issue #489.